requires "Kossy", 0.38;
requires "DBIx::Sunny";

requires "DBD::mysql";
requires "Starman";
requires "Plack::Session";
requires "Path::Class";

requires "Gazelle";
requires "Server::Starter";
requires "Gearman::Server";
requires "Gearman::Worker";
requires "Parallel::Prefork";
requires "Data::MessagePack";
