#!/usr/bin/env perl
use strict;
use warnings;

chdir '/home/isucon/webapp/perl';

$ENV{LANG} = 'C';
warn "worker_run_init";

open STDERR, '>&STDOUT'; $| = 1;
exec(
    'setuidgid',
    'isucon',
    '/home/isucon/.local/perl/bin/carton',
    'exec',
    '--',
    '/home/isucon/.local/perl/bin/perl',
    '-Ilib',
    'worker.pl',
);
